/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openccjni_OpenccWrapper */

#ifndef _Included_openccjni_OpenccWrapper
#define _Included_openccjni_OpenccWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     openccjni_OpenccWrapper
 * Method:    opencc_abi_number
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_openccjni_OpenccWrapper_opencc_1abi_1number
  (JNIEnv *, jclass);

/*
 * Class:     openccjni_OpenccWrapper
 * Method:    opencc_version_string
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_openccjni_OpenccWrapper_opencc_1version_1string
  (JNIEnv *, jclass);

/*
 * Class:     openccjni_OpenccWrapper
 * Method:    opencc_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_openccjni_OpenccWrapper_opencc_1new
  (JNIEnv *, jobject);

/*
 * Class:     openccjni_OpenccWrapper
 * Method:    opencc_convert
 * Signature: (J[B[BZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_openccjni_OpenccWrapper_opencc_1convert
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jboolean);

/*
 * Class:     openccjni_OpenccWrapper
 * Method:    opencc_get_parallel
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_openccjni_OpenccWrapper_opencc_1get_1parallel
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openccjni_OpenccWrapper
 * Method:    opencc_set_parallel
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_openccjni_OpenccWrapper_opencc_1set_1parallel
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     openccjni_OpenccWrapper
 * Method:    opencc_zho_check
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_openccjni_OpenccWrapper_opencc_1zho_1check
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     openccjni_OpenccWrapper
 * Method:    opencc_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_openccjni_OpenccWrapper_opencc_1delete
  (JNIEnv *, jobject, jlong);

/*
 * Class:     openccjni_OpenccWrapper
 * Method:    opencc_last_error
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_openccjni_OpenccWrapper_opencc_1last_1error
  (JNIEnv *, jobject);

/*
 * Class:     openccjni_OpenccWrapper
 * Method:    opencc_convert_cfg
 * Signature: (J[BIZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_openccjni_OpenccWrapper_opencc_1convert_1cfg
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jboolean);

/*
 * Class:     openccjni_OpenccWrapper
 * Method:    opencc_config_name_to_id
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_openccjni_OpenccWrapper_opencc_1config_1name_1to_1id
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     openccjni_OpenccWrapper
 * Method:    opencc_config_id_to_name
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_openccjni_OpenccWrapper_opencc_1config_1id_1to_1name
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
